Proofread convention
rezoleo/Convention_AGR pull request #1
Opened 2017-05-28 16:39 UTC by tikiki

2017-05-28 17:41 UTC, tdenof requested changes

2017-05-28 17:41 UTC, tdenof commented on convention_agr.tex
> +    Le Rézoléo s'engage à pourvoir aux obligations prévues par la loi dans le cadre de la seule exploitation technique du réseau informatique. À ce titre, le Rézoléo s'engage à garder trace des noms
"pour une période d'un an" au lieu de "durant un délai de 1 an".

2017-05-28 17:41 UTC, tdenof commented on convention_agr.tex
> +    En cas de risque majeur pour l'intégrité du réseau de la Résidence, le Président du Rézoléo s'engage à en avertir dans les plus brefs délais un représentant de l'AGR. Il proposera si possible un
corriger plutôt que surmonter ?

2017-05-28 17:41 UTC, tdenof commented on convention_agr.tex
> +    Le Rézoléo notifie une semaine à l'avance toute intervention sur l'électricité, les fluides ou les locaux.\\
Que veut-on dire par intervention dans les locaux ?

2017-05-28 17:41 UTC, tdenof commented on convention_agr.tex
>      Le Rézoléo s'engage suite à sa période d'essai à racheter progressivement, dans la mesure du possible, l'ensemble des équipements informatiques mis à disposition par l'AGR, en prenant en compte l
techniques*

2017-05-28 17:41 UTC, tdenof commented on convention_agr.tex
> +    Le Rézoléo s'engage en tout état de cause, si l'association arrête l'exploitation des réseaux des Résidences AGR, de prévenir au moins trois mois à l'avance la direction d'AGR de cette décision p
de l'AGR*

2017-05-28 17:41 UTC, tdenof commented on convention_agr.tex
>      Les serveurs, outillage de maintenance, les switchs situés en dehors des locaux techniques sont la propriété du Rézoléo.
"le matériel informatique situé en dehors des locaux techniques" plutôt que "les switchs" ?

2017-05-28 17:52 UTC, tikiki commented on convention_agr.tex
> +    Le Rézoléo notifie une semaine à l'avance toute intervention sur l'électricité, les fluides ou les locaux.\\
@NBKZiman

2017-05-29 21:04 UTC, NBKZiman commented on convention_agr.tex
> +    Le Rézoléo notifie une semaine à l'avance toute intervention sur l'électricité ou les fluides dans les locaux.\\
@tdenof

2017-05-29 21:05 UTC, NBKZiman approved these changes

2017-05-30 22:13 UTC, merged